### ISSUE TITLE
Having empty spaces in my data

### ISSUE THREAD

**Issue by hannita2020** [nathwright98/csvcombi.py#1]
Hiya! First of all thank you so much for this it's really helped! I was just wondering if there was any way to still run the code when my data has spaces? I'm quite new to python so vey much an amateur I'm afraid x

**Comment by nathwright98** [comment]
Hi @hannita2020, thanks for raising this issue. As of release 0.2.0 this functionality should be added and data with spaces should be ignored as part of the reduction process.
